version: '3.8'

services:
  api_db:
    image: mysql:8.0.30
    container_name: api_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL="true"
      - MYSQL_USE_SSL="false"
      - TZ=America/Manaus
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  api_app:
    build: .
    container_name: api_app
    depends_on:
      - api_db
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    command: [ "npm", "run", "dev" ]